### ISSUE TITLE
Añadiendo dinamismo al cliente desde Elixir con Frankt

### ISSUE THREAD

**Issue by crbelaus** [elixirasturias/propuestas#1]
# Topic principal de la propuesta

Añadiendo dinamismo al cliente desde Elixir con Frankt

# Breve descripción

Frankt es una pequeña librería que se apoya en la funcionalidad de Channels y Sockets de Phoenix Framework para permitirnos ejecutar eventos en el cliente desde el backend, por ejemplo: 
- Recibir información del cliente en nuestro backend sin necesidad de JS ni Ajax.
- Utilizar esta información para modificar partes del DOM desde el backend.
- Lanzar modificaciones del DOM desde procesos largos que se estén ejecutando en el backend.
- Extender las acciones por defecto de Frankt con nuevas acciones personalizadas.

Antes de entrar en detalle sobre cómo funciona Frankt y qué nos permite, haremos una pequeña introducción a Phoenix Framework así como a los Channels.

# Materiales necesarios para desarrollarla (proyectores, sala...)

En principio nos sirve con una sala que tenga proyector y conexión a Internet.

# Referencias
- [Frankt](https://github.com/acutario/frankt)
- [Phoenix Framework](http://phoenixframework.org/)
- [Elixir](https://elixir-lang.org/)

**Comment by dreamingechoes** [comment]
Charla celebrada, ¡cerramos issue! :smile:

**Comment by crbelaus** [comment]
Dejo aquí [las diapositivas de la charla][1] y algunos enlaces que pueden ser interesantes.

- [Drab: Remote controlled frontend framework for Phoenix][2]
- [Phoenix WebSockets under a microscope][3]
- [RFC6455 The WebSocket protocol][4]
- [WebSocket support across different browsers][5]

[1]: https://github.com/elixirasturias/propuestas/files/2195098/Dinamizando.el.cliente.con.Frankt.pdf
[2]: https://github.com/grych/drab
[3]: https://zorbash.com/post/phoenix-websockets-under-a-microscope/
[4]: https://tools.ietf.org/html/rfc6455
[5]: https://caniuse.com/#feat=websockets
