### ISSUE TITLE
Introducción a Elixir: Chat con Phoenix paso a paso

### ISSUE THREAD

**Issue by martamedio** [elixirasturias/propuestas#3]
# Topic principal de la propuesta
Introducción a Elixir: Chat con Phoenix paso a paso

# Breve descripción
Charla totalmente introductoria a Elixir, donde desarrollaré paso a paso como ejemplo un sistema de chat con _Phoenix Framework_ usando el generador `mix phx.new` y un almacenamiento en _PostgreSQL_

# Materiales necesarios para desarrollarla (proyectores, sala...)
Proyector y conexión a internet

# Referencias
- [Elixir](https://elixir-lang.org/)
- [Elixir School](https://elixirschool.com/es/lessons/basics/basics/)
- [Phoenix Framework](http://phoenixframework.org/)

**Comment by dreamingechoes** [comment]
Charla celebrada, ¡cerramos issue! 😄
