### ISSUE TITLE
En busca del endpoint perdido: mi primera API en Elixir

### ISSUE THREAD

**Issue by noeliaena** [elixirasturias/propuestas#4]
# Topic principal de la propuesta
En busca del endpoint perdido: mi primera API en Elixir. 

# Breve descripción
Implementación de una RESTful API sencilla en Elixir, donde contaré el paso a paso y los temas más interesantes del desarrollo, desde un punto de vista introductorio.

# Materiales necesarios para desarrollarla (proyectores, sala...)
Proyector y conexión a internet.

# Referencias
* [Elixir](https://elixir-lang.org/)

**Comment by dreamingechoes** [comment]
Charla celebrada, ¡cerramos issue! 😄
